import = ["~/.config/alacritty/dark.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 13
