import = ["~/.config/alacritty/tokyonight_night.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.65
blur = true
option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 11
