
[env]
TERM = "xterm-256color"

[window]
padding.x = 3
padding.y = 3 
# decorations = "Buttonless"
option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 13

[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin-latte.toml"]
